[package]
name = "trin-state"
version = "0.1.0"
authors = ["Jason Carver <ut96caarrs@snkmail.com>"]
edition = "2021"
rust-version = "1.58.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.52"
discv5 = "0.1.0-beta.13"
ethereum-types = "0.12.0"
eth_trie = "0.1.0"
hex = "0.4.3"
log = "0.4.14"
num = "0.4.0"
serde_json = "1.0.59"
tracing = "0.1.26"
tracing-subscriber = "0.2.18"
tracing-futures = "0.2.5"
tokio = {version = "1.18.4", features = ["full"]}
trin-core = { path = "../trin-core" }
rocksdb = "0.16.0"
